sonar.organization=aws_aws-sdk-java-v2
sonar.projectKey=aws
sonar.projectName=Ocean Tide Drop AI SURFER

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8

