# wrangler
name = 'aisurfer2'
main = "src/index.ts" # or wherever your entry point is
compatibility_date = "2024-03-01"
run_worker_first = ["/api/*"]
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1




[vars]
# Firebase (safe)
VITE_FIREBASE_API_KEY = "AIzaSyB-ESc7O76NImSsdspCWIP6zygLwuWkDm0"
VITE_FIREBASE_AUTH_DOMAIN = "otd-ai-surfer.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "otd-ai-surfer"
VITE_FIREBASE_STORAGE_BUCKET = "otd-ai-surfer.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "46473040430"
VITE_FIREBASE_APP_ID = "1:46473040430:web:8438a456c93831be0605bf"

# Supabase (safe)
VITE_SUPABASE_URL = "https://cctobgbyxjfabksnokbe.supabase.co"
VITE_SUPABASE_ANON_KEY = "sb_publishable_MMlDjds0mfsZR4_0pjaUVw_bBqm_BJt"

# Google (safe if restricted)
VITE_GOOGLE_API_KEY = "AIzaSyAiBe63QZb981xejojML7zqfQXfXhEn9Qk"
